### ISSUE TITLE
Unit Tests failing on iPhone and Safari 9.1

### ISSUE THREAD

**Issue by agubler** [dojo/shim#96]
**Bug**

Unit tests are failing for iPhone and Safari 9.1 on browserstack.

```
× safari 9.1 on MAC - unit tests - queue functions - .queueMicroTask() (0.305s)
AssertionError: expected -1 to equal 0
  at AssertionError  <__intern/browser_modules/chai/chai.js:5553:27>
  at assert  <__intern/browser_modules/chai/chai.js:206:31>
  at equal  <__intern/browser_modules/chai/chai.js:2277:16>
  at <tests/unit/support/queue.ts:147:16>
  at <__intern/lib/util.js:555:38>
  at <__intern/lib/util.js:568:28>
>> safari 9.1 on MAC: 1/345 tests failed (1 skipped)

× iPhone 9.1 on any platform - Async/Await with Bluebird (1.001s)
AssertionError: expected { Object (result, wasThrown) } to equal 42
  at Function.assert.equal  <node_modules/intern/browser_modules/chai/chai.js:2277:10>
  at Command.<anonymous>  <tests/functional/asyncAwait.ts:14:11>
  at runCallback  <node_modules/leadfoot/Command.js:526:31>
  at Command.<anonymous>  <node_modules/leadfoot/Command.js:543:11>
  at <node_modules/dojo/Promise.ts:393:15>
  at run  <node_modules/dojo/Promise.ts:237:7>
  at <node_modules/dojo/nextTick.ts:44:3>
  at _combinedTickCallback  <internal/process/next_tick.js:73:7>
  at process._tickCallback  <internal/process/next_tick.js:104:9>
  at Command.then  <node_modules/leadfoot/Command.js:542:10>
  at Test.Async/Await with Bluebird [as test]  <tests/functional/asyncAwait.ts:13:4>
  at <node_modules/intern/lib/Test.js:191:24>
  at <node_modules/intern/browser_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/browser_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/browser_modules/dojo/Promise.ts:317:4>
  at run  <node_modules/intern/browser_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/browser_modules/dojo/nextTick.ts:44:3>
  at _combinedTickCallback  <internal/process/next_tick.js:73:7>
  at process._tickCallback  <internal/process/next_tick.js:104:9>
× iPhone 9.1 on any platform - Async/Await with Dojo (1.006s)
AssertionError: expected { Object (result, wasThrown) } to equal 42
  at Function.assert.equal  <node_modules/intern/browser_modules/chai/chai.js:2277:10>
  at Command.<anonymous>  <tests/functional/asyncAwait.ts:25:11>
  at runCallback  <node_modules/leadfoot/Command.js:526:31>
  at Command.<anonymous>  <node_modules/leadfoot/Command.js:543:11>
  at <node_modules/dojo/Promise.ts:393:15>
  at run  <node_modules/dojo/Promise.ts:237:7>
  at <node_modules/dojo/nextTick.ts:44:3>
  at _combinedTickCallback  <internal/process/next_tick.js:73:7>
  at process._tickCallback  <internal/process/next_tick.js:104:9>
  at Command.then  <node_modules/leadfoot/Command.js:542:10>
  at Test.Async/Await with Dojo [as test]  <tests/functional/asyncAwait.ts:24:4>
  at <node_modules/intern/lib/Test.js:191:24>
  at <node_modules/intern/browser_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/browser_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/browser_modules/dojo/Promise.ts:317:4>
  at run  <node_modules/intern/browser_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/browser_modules/dojo/nextTick.ts:44:3>
  at _combinedTickCallback  <internal/process/next_tick.js:73:7>
  at process._tickCallback  <internal/process/next_tick.js:104:9>
× iPhone 9.1 on any platform - Async/Await with Bluebird and Dojo (1.113s)
AssertionError: expected { Object (result, wasThrown) } to equal 42
  at Function.assert.equal  <node_modules/intern/browser_modules/chai/chai.js:2277:10>
  at Command.<anonymous>  <tests/functional/asyncAwait.ts:36:11>
  at runCallback  <node_modules/leadfoot/Command.js:526:31>
  at Command.<anonymous>  <node_modules/leadfoot/Command.js:543:11>
  at <node_modules/dojo/Promise.ts:393:15>
  at run  <node_modules/dojo/Promise.ts:237:7>
  at <node_modules/dojo/nextTick.ts:44:3>
  at _combinedTickCallback  <internal/process/next_tick.js:73:7>
  at process._tickCallback  <internal/process/next_tick.js:104:9>
  at Command.then  <node_modules/leadfoot/Command.js:542:10>
  at Test.Async/Await with Bluebird and Dojo [as test]  <tests/functional/asyncAwait.ts:35:4>
  at <node_modules/intern/lib/Test.js:191:24>
  at <node_modules/intern/browser_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/browser_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/browser_modules/dojo/Promise.ts:317:4>
  at run  <node_modules/intern/browser_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/browser_modules/dojo/nextTick.ts:44:3>
  at _combinedTickCallback  <internal/process/next_tick.js:73:7>
  at process._tickCallback  <internal/process/next_tick.js:104:9>
>> iPhone 9.1 on any platform: 3/345 tests failed (1 skipped)
```

**Comment by kitsonk** [comment]
These issues seemed to be BrowserStack environmental and have abated.  Can we close this?

**Comment by kitsonk** [comment]
This test does appear to be fragile though:

```
× safari 9.1 on MAC - unit tests - queue functions - .queueMicroTask() (0.305s)
AssertionError: expected -1 to equal 0
  at AssertionError  <__intern/browser_modules/chai/chai.js:5553:27>
  at assert  <__intern/browser_modules/chai/chai.js:206:31>
  at equal  <__intern/browser_modules/chai/chai.js:2277:16>
  at <tests/unit/support/queue.ts:147:16>
  at <__intern/lib/util.js:555:38>
  at <__intern/lib/util.js:568:28>
>> safari 9.1 on MAC: 1/345 tests failed (1 skipped)
```

We may need to dig into how tasks are scheduled in Safari a bit deeper to get predictable results.
